name       : bam
version    : 0.4.0
release    : 2
source     :
    - http://github.com/downloads/matricks/bam/bam-0.4.0.tar.bz2 : 56030670aa21e227ce0a00f1ee0c9b5129469a6e69e7b67c3dd459d2fce6207d
license    : Zlib
component  : programming.tools
summary    : Bam is a build system
description: |
    Bam is a build system with the focus on being having fast build times and flexiable build scripts. Instead of having a custom language it uses Lua to describe the build steps.
builddeps  :
    - pkgconfig(lua-5.3)
build      : |
    ./make_unix.sh
install    : |
    install -D -m 00755 bam $installdir/usr/bin/bam
